import { ScanItem, Screen } from "../App";
import { ArrowRight, Info } from "lucide-react";

interface Props {
  scan: ScanItem;
  navigate: (s: Screen) => void;
}

export function FeatureAnalysisScreen({ scan, navigate }: Props) {
  const features = [
    {
      key: "asymmetry",
      label: "Asymmetry",
      score: scan.abcd.asymmetry,
      desc: "Measures whether the mole is symmetrical. Higher scores indicate greater asymmetry, a key melanoma indicator.",
      threshold: 50,
    },
    {
      key: "border",
      label: "Border Irregularity",
      score: scan.abcd.border,
      desc: "Evaluates edge definition. Irregular, ragged, or blurred borders may suggest malignancy.",
      threshold: 50,
    },
    {
      key: "color",
      label: "Color Variation",
      score: scan.abcd.color,
      desc: "Detects multiple shades within the lesion. Varied pigmentation patterns are clinically significant.",
      threshold: 55,
    },
    {
      key: "diameter",
      label: "Diameter",
      score: scan.abcd.diameter,
      desc: "Estimates relative lesion size. Lesions larger than 6 mm warrant closer monitoring.",
      threshold: 45,
    },
  ];

  const getScoreColor = (score: number, threshold: number) => {
    if (score >= threshold + 20) return { bar: "#f87171", text: "#f87171", label: "Elevated" };
    if (score >= threshold) return { bar: "#facc15", text: "#facc15", label: "Moderate" };
    return { bar: "#4ade80", text: "#4ade80", label: "Normal" };
  };

  return (
    <div
      className="min-h-[calc(100vh-4rem)] px-4 py-10"
      style={{ backgroundColor: "#0F1629" }}
    >
      <div className="max-w-3xl mx-auto">
        <div className="mb-8">
          <h1 className="text-2xl font-bold text-white" style={{ fontWeight: 700 }}>
            ABCD Feature Analysis
          </h1>
          <p className="text-sm mt-1" style={{ color: "#9CA3AF" }}>
            AI-extracted dermoscopic feature scores based on the clinical ABCD rule.
          </p>
        </div>

        {/* ABCD Info Banner */}
        <div
          className="p-4 rounded-2xl border mb-8 flex items-start gap-3"
          style={{
            backgroundColor: "rgba(31,42,86,0.4)",
            borderColor: "rgba(58,63,122,0.4)",
          }}
        >
          <Info size={16} style={{ color: "#9B3C7A", flexShrink: 0, marginTop: 2 }} />
          <p className="text-xs leading-relaxed" style={{ color: "#D1D5DB" }}>
            The <strong className="text-white">ABCD rule</strong> (Asymmetry, Border, Color, Diameter) is a
            validated clinical method for evaluating pigmented skin lesions. Scores are generated by
            YOLOv11's feature extraction pipeline and should be interpreted alongside professional consultation.
          </p>
        </div>

        {/* Feature Cards */}
        <div className="space-y-4 mb-8">
          {features.map((feat) => {
            const { bar, text, label } = getScoreColor(feat.score, feat.threshold);
            return (
              <div
                key={feat.key}
                className="p-6 rounded-2xl border"
                style={{ backgroundColor: "#1a2240", borderColor: "rgba(58,63,122,0.4)" }}
              >
                <div className="flex items-center justify-between mb-3">
                  <div>
                    <h3 className="font-semibold text-white">{feat.label}</h3>
                    <p className="text-xs mt-0.5" style={{ color: "#9CA3AF" }}>
                      {feat.desc}
                    </p>
                  </div>
                  <div className="text-right flex-shrink-0 ml-4">
                    <div className="text-2xl font-bold text-white">{feat.score}</div>
                    <span
                      className="text-xs px-2 py-0.5 rounded-full"
                      style={{ backgroundColor: `${bar}20`, color: text }}
                    >
                      {label}
                    </span>
                  </div>
                </div>

                {/* Progress bar */}
                <div
                  className="w-full h-2.5 rounded-full overflow-hidden"
                  style={{ backgroundColor: "rgba(58,63,122,0.3)" }}
                >
                  <div
                    className="h-full rounded-full transition-all"
                    style={{ width: `${feat.score}%`, backgroundColor: bar }}
                  />
                </div>

                <div className="flex justify-between text-xs mt-1.5" style={{ color: "#9CA3AF" }}>
                  <span>0 — Normal</span>
                  <span>100 — Elevated</span>
                </div>
              </div>
            );
          })}
        </div>

        {/* Overall score */}
        <div
          className="p-6 rounded-2xl border mb-6"
          style={{ backgroundColor: "#1F2A56", borderColor: "rgba(155,60,122,0.3)" }}
        >
          <p className="text-sm font-medium text-white mb-2">Overall ABCD Score</p>
          <div className="flex items-center gap-4">
            <div className="text-4xl font-bold text-white">
              {Math.round(
                (scan.abcd.asymmetry + scan.abcd.border + scan.abcd.color + scan.abcd.diameter) / 4
              )}
              <span className="text-lg text-white">/100</span>
            </div>
            <p className="text-sm" style={{ color: "#D1D5DB" }}>
              Composite score derived from all four ABCD dimensions extracted by YOLOv11.
            </p>
          </div>
        </div>

        <button
          onClick={() => navigate("risk-assessment")}
          className="flex items-center justify-center gap-2 w-full py-3.5 rounded-xl font-semibold text-white"
          style={{ backgroundColor: "#9B3C7A" }}
          onMouseEnter={(e) => e.currentTarget.style.backgroundColor = "#7d3063"}
          onMouseLeave={(e) => e.currentTarget.style.backgroundColor = "#9B3C7A"}
        >
          View Risk Assessment
          <ArrowRight size={18} />
        </button>
      </div>
    </div>
  );
}
